services:
  db:
    image: postgres:latest
    container_name: lmw_fitness_db
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - lmw-fitness-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: lmwcode/lmw_fitness_api:v1.0.0
    container_name: lmw_fitness_api
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
    secrets:
      - db_password_secret
    ports:
      - "8082:8082"
    networks:
      - lmw-fitness-network

networks:
  lmw-fitness-network:
    driver: bridge

volumes:
  db-data: