package database

import (
	"log"

	"github.com/88warren/lmw-fitness-backend/models"
	"gorm.io/gorm"
)

func ExerciseSeed() {

	log.Println("Seeding workout data...")

	exercises := []models.Exercise{
		// Placeholder exercise until have these videos
		// {
		// 	Name:         "Wall Press Ups",
		// 	Description:  "A modified press up for beginners, using a wall for support.",
		// 	Category:     "upper_body",
		// 	VideoID:      "your_wall_pressup_video_id",
		// 	Tips:         "Keep your body in a straight line, hands slightly wider than shoulder-width, and engage your core.",
		// 	Instructions: "Place your hands against a wall, shoulder-width apart. Lean in and perform a press up motion, then press back out.",
		// },
		// {
		// 	Name:         "Incline Press Ups",
		// 	Description:  "A modified press up performed with hands on an elevated surface.",
		// 	Category:     "upper_body",
		// 	VideoID:      "your_incline_pressup_video_id",
		// 	Tips:         "The higher the surface, the easier the exercise. Keep your body straight and lower your chest to the surface.",
		// 	Instructions: "Place your hands on a stable elevated surface (like a bench or chair) and perform a press up.",
		// },
		// {
		// 	Name:         "Decline Press Ups",
		// 	Description:  "An advanced press up variation with feet elevated.",
		// 	Category:     "upper_body",
		// 	VideoID:      "your_decline_pressup_video_id",
		// 	Tips:         "Keep your core tight to prevent your hips from sagging. The higher your feet, the more challenging the exercise.",
		// 	Instructions: "Place your feet on an elevated surface and your hands on the floor. Perform a press up.",
		// },
		// {
		// 	Name:         "Side Plank (Right)",
		// 	Description:  "Isometric core exercise targeting the obliques on the right side.",
		// 	Category:     "core",
		// 	VideoID:      "your_side_plank_right_video_id",
		// 	Tips:         "Stack your feet, keep your body in a straight line from head to toe, and don't let your hips sag.",
		// 	Instructions: "Lie on your right side, propped up on your right forearm, and lift your hips off the floor. Hold the position.",
		// },
		// {
		// 	Name:         "Side Plank (Left)",
		// 	Description:  "Isometric core exercise targeting the obliques on the left side.",
		// 	Category:     "core",
		// 	VideoID:      "your_side_plank_left_video_id",
		// 	Tips:         "Stack your feet, keep your body in a straight line from head to toe, and don't let your hips sag.",
		// 	Instructions: "Lie on your left side, propped up on your left forearm, and lift your hips off the floor. Hold the position.",
		// },
		// {
		// 	Name:         "Squat Walks",
		// 	Description:  "A walking variation of a squat to target the glutes and hips.",
		// 	Category:     "legs",
		// 	VideoID:      "your_squat_walks_video_id",
		// 	Tips:         "Stay low in the squat position and take small, controlled steps forward and backward or side to side.",
		// 	Instructions: "Enter a low squat position and take small steps, maintaining the squat depth throughout the movement.",
		// },
		// {
		// 	Name:         "Pistol Squat",
		// 	Description:  "A unilateral leg exercise performed on one leg.",
		// 	Category:     "legs",
		// 	VideoID:      "your_pistol_squat_video_id",
		// 	Tips:         "Requires significant balance and leg strength. Start with assistance (holding onto a door frame) if needed.",
		// 	Instructions: "Stand on one leg, extend the other leg out, and lower into a deep squat. Return to standing position.",
		// },
		// {
		// 	Name:         "Broad Jumps to Back Pedal",
		// 	Description:  "A plyometric exercise for power and agility.",
		// 	Category:     "cardio",
		// 	VideoID:      "your_broad_jumps_back_pedal_video_id",
		// 	Tips:         "Land softly with your knees bent. Quickly pedal backward to the starting position.",
		// 	Instructions: "Perform a broad jump forward, then quickly backpedal to the starting point.",
		// },

		// Real time videos
		{
			Name:         "Mobility",
			Description:  "Stretch off all muscles",
			Category:     "full_body",
			VideoID:      "wAeJIXugbz4",
			Tips:         "Don't bounce during the stretch, hold for the duration.",
			Instructions: "Hold each pose for 1 -3 minutes. Help aid recovery and flexibility",
		},
		{
			Name:         "Cool Down",
			Description:  "Stretch off all muscles",
			Category:     "full_body",
			VideoID:      "qB1whwZllzI",
			Tips:         "Don't bounce during the stretch, hold for the duration.",
			Instructions: "Hold each pose for 10-15seconds. Remove lactic acid and aid recovery",
		},
		{
			Name:         "Warm Up",
			Description:  "Dynamic whole body warm up",
			Category:     "full_body",
			VideoID:      "R9EPu3nhvhA",
			Tips:         "Move through each exercise ensuring you have warmed up the whole body",
			Instructions: "Quick 5 minute blast to get the muscles warm and the heart rate elevated.",
		},
		{
			Name:         "Tricep Dips (with Chair)",
			Description:  "A bodyweight exercise to target the triceps using a chair.",
			Category:     "upper_body",
			VideoID:      "idHOHRRAbZ0",
			Tips:         "Keep your back close to the chair. You can make it easier by keeping your knees bent or harder by extending your legs.",
			Instructions: "Place your hands on a chair behind you, with your knees bent. Lower your body down and then push back up.",
		},
		{
			Name:         "Plank Hold",
			Description:  "Isometric core exercise",
			Category:     "core",
			VideoID:      "daVdrP15_nI",
			Tips:         "Engage core, avoid sagging hips and breathe steadily.",
			Instructions: "Hold plank position with straight body from head to heels.",
		},
		{
			Name:         "Diamond Press Ups",
			Description:  "Advanced press up variation",
			Category:     "upper_body",
			VideoID:      "6_yaoroohq0",
			Tips:         "Form a diamond shape with hands, lower chest to hands, keep body straight.",
			Instructions: "Place hands in diamond shape under chest, perform press ups.",
		},
		{
			Name:         "Diamond Press Ups (on Knees)",
			Description:  "Modified advanced press up variation",
			Category:     "upper_body",
			VideoID:      "Ro8aGAyeDRE",
			Tips:         "Form a diamond shape with hands, lower chest to hands, keep body straight, whilst on knees.",
			Instructions: "Place hands in diamond shape under chest, perform press ups on knees.",
		},
		{
			Name:         "Wall Sits",
			Description:  "Isometric leg exercise",
			Category:     "legs",
			VideoID:      "EyTkL4gbXKs",
			Tips:         "Keep your back flat against the wall and your thighs parallel to the ground, as if sitting in a chair.",
			Instructions: "Slide your back down a wall until your knees are bent at a 90-degree angle. Hold the position.",
		},
		{
			Name:         "Sit Ups",
			Description:  "Standard abdominal exercise.",
			Category:     "core",
			VideoID:      "65IV78T82zA",
			Tips:         "Keep your neck neutral and use your core to lift your body, not your neck or shoulders.",
			Instructions: "Lie on your back with knees bent, feet on the floor. Lift your upper body toward your knees.",
		},
		{
			Name:         "Wide Arm Press Ups (on Knees)",
			Description:  "A modified press up with a wide hand position.",
			Category:     "upper_body",
			VideoID:      "J-M8Yo43S0E",
			Tips:         "Keep your hands wider than your shoulders and lower your chest to the floor. Maintain a straight back.",
			Instructions: "Place your hands wide on the floor, on your knees and perform a press up.",
		},
		{
			Name:         "Hollow Hold",
			Description:  "An advanced isometric core exercise for stability.",
			Category:     "core",
			VideoID:      "ArggQLa_4tM",
			Tips:         "Keep your lower back pressed into the floor. The lower your limbs, the more challenging it becomes.",
			Instructions: "Lie on your back, lift your head, shoulders and legs off the floor, forming a 'hollow' shape with your body. Hold.",
		},
		{
			Name:         "Squat Hold",
			Description:  "An isometric exercise to build leg and core endurance.",
			Category:     "legs",
			VideoID:      "MiBb0Cy7zIU",
			Tips:         "Keep your chest up and your back straight, with your weight in your heels. Breathe steadily.",
			Instructions: "Lower into a squat position and hold it for the designated time.",
		},
		{
			VideoID:      "D_NnuO52648",
			Name:         "Press Up Twists (on Knees)",
			Category:     "upper_body",
			Description:  "A press up variation that adds a torso twist for core engagement.",
			Tips:         "As you twist, stack your hips and open your chest to the side. Keep your core engaged to prevent wobbling.",
			Instructions: "Perform a press up on your knees, and at the top, twist your torso to one side, raising one arm to the ceiling.",
		},
		{
			VideoID:      "8r164zBaPyI",
			Name:         "H.O.G. Press Ups (on Knees)",
			Category:     "upper_body",
			Description:  "A press up variation focusing on full range from your knees.",
			Tips:         "H.O.G. stands for 'Hands Off the Ground.' To help focus on full range.",
			Instructions: "Perform a press up from your knees and lower all the way to the ground. Make sure your hands leave the ground and push back up.",
		},
		{
			VideoID:      "zkC41M7uv04",
			Name:         "Squats",
			Category:     "legs",
			Description:  "Basic bodyweight squats",
			Tips:         "Keep chest up, knees over toes, go as low as comfortable.",
			Instructions: "Stand with feet shoulder-width apart, lower your body as if sitting back into a chair.",
		},
		{
			VideoID:      "Dy11nVeveDI",
			Name:         "Y Shaped Lunges",
			Category:     "legs",
			Description:  "A dynamic lunge variation that targets multiple leg and glute muscles.",
			Tips:         "Raise your arms above your head, creating a 'Y' shape, stepping forward. Maintain control.",
			Instructions: "Perform a lunge by stepping forward, with your arms straight up in the air.",
		},
		{
			VideoID:      "YuVKqlYm5Aw",
			Name:         "Wide Arm Press Ups",
			Category:     "upper_body",
			Description:  "A press up variation that emphasizes the chest muscles.",
			Tips:         "Place your hands wider than shoulder-width. Lower your chest to the floor, keeping your elbows out.",
			Instructions: "Start in a high plank position with hands wide and perform a press up.",
		},
		{
			VideoID:      "TQaP1Uldqk8",
			Name:         "Walkaways",
			Category:     "full_body",
			Description:  "Dynamic movement that strengthens the core, shoulders, and arms.",
			Tips:         "Keep your core tight and your hips from sagging. Walk your hands as far out as you can, perform a press up, then walk them back.",
			Instructions: "From a standing position, bend down and walk your hands out into a plank, perform a press up, then walk your hands back to standing.",
		},
		{
			VideoID:      "YcEIPmeX3Tg",
			Name:         "V Press Ups",
			Category:     "upper_body",
			Description:  "A press up variation that targets the shoulders.",
			Tips:         "Form an inverted V-shape with your body. Lower your head toward your hands, keeping your elbows in.",
			Instructions: "Start in a high plank, lift your hips to form an inverted V and perform a press up.",
		},
		{
			VideoID:      "sy13VWfmY3E",
			Name:         "Upward Dog",
			Category:     "yoga",
			Description:  "A yoga pose for stretching the chest and hip flexors.",
			Tips:         "Press into your hands and the tops of your feet. Keep your shoulders down and away from your ears.",
			Instructions: "From a prone position, press into your hands to lift your chest and thighs off the floor.",
		},
		{
			VideoID:      "midgeskmYto",
			Name:         "Tuck Jumps",
			Category:     "cardio",
			Description:  "A plyometric exercise for explosive power.",
			Tips:         "Land softly with bent knees. Try to bring your knees as high as possible on each jump.",
			Instructions: "Jump up, tucking your knees to your chest in mid-air. Land softly and repeat.",
		},
		{
			VideoID:      "4q9T61x1lVQ",
			Name:         "Tricep Extensions",
			Category:     "upper_body",
			Description:  "An exercise to isolate and strengthen the triceps.",
			Tips:         "Keep your forearms flat on the floor, push through your hands and straighten your arms, squeezing your triceps.",
			Instructions: "Extend your arms fully, then bend your elbows to lower your forearms. Press back up.",
		},
		{
			VideoID:      "XOwiwAbSJ9U",
			Name:         "Tricep Dips (Floor)",
			Category:     "upper_body",
			Description:  "A bodyweight exercise for the triceps.",
			Tips:         "Keep your back straight and close to the bench or floor. Lower until your upper arms are parallel to the floor.",
			Instructions: "Place your hands on a bench or the floor behind you. Lower your body by bending your elbows, then press back up.",
		},
		{
			VideoID:      "a9YlX8xWN8A",
			Name:         "Tricep Dips Right Leg (Floor)",
			Category:     "upper_body",
			Description:  "A tricep dip variation with the right leg extended for added challenge.",
			Tips:         "Keep your right leg straight and focus on keeping your hips high. Maintain a steady tempo.",
			Instructions: "Perform a tricep dip while extending your right leg straight out in front of you.",
		},
		{
			VideoID:      "aM4BFF7ANRk",
			Name:         "Tricep Dips Left Leg (Floor)",
			Category:     "upper_body",
			Description:  "A tricep dip variation with the left leg extended for added challenge.",
			Tips:         "Keep your left leg straight and focus on keeping your hips high. Maintain a steady tempo.",
			Instructions: "Perform a tricep dip while extending your left leg straight out in front of you.",
		},
		{
			VideoID:      "Ef5nlg3d7Ic",
			Name:         "Toe Taps",
			Category:     "core",
			Description:  "A core exercise that strengthens the abs.",
			Tips:         "Keep your lower back pressed firmly into the floor. Keep your legs straight up in the air.",
			Instructions: "Lie on your back with your legs raised. Reach as far up your leg as possible, ideally your toes. Repeat.",
		},
		{
			VideoID:      "WIm84bfsznc",
			Name:         "Thrusters",
			Category:     "full_body",
			Description:  "A dynamic full-body exercise.",
			Tips:         "Keep your arms strong and steady, move explosively, bring your knees as far towards your chest as your can. Don't sag your back.",
			Instructions: "Start in a press up position and bring both your feet up towards your chest. Drive through you hands and return your feet to the starting position.",
		},
		{
			VideoID:      "ueqyaNH24Dc",
			Name:         "T-Runs",
			Category:     "cardio",
			Description:  "An agility drill involving sprinting and quick changes of direction.",
			Tips:         "Focus on quick footwork and a low center of gravity when changing directions.",
			Instructions: "Sprint forward, then shuffle sideways to the left, and then backpedal to the start, and repeat on the left, forming a 'T' shape.",
		},
		{
			VideoID:      "cU0uPUXoee4",
			Name:         "Switch Kicks",
			Category:     "cardio",
			Description:  "A cardio exercise that involves quick, alternating kicks.",
			Tips:         "Keep your core engaged to maintain balance. The kicks should be fast and controlled.",
			Instructions: "Sit on the floor with your arms behind you, knees bent, lift your bum off the floor. Perform alternating series of light kicks.",
		},
		{
			VideoID:      "XPzg-PqP2vE",
			Name:         "Superman",
			Category:     "core",
			Description:  "A core exercise that strengthens the back, glutes and shoulders.",
			Tips:         "Focus on lifting with your back and glutes. Keep your head in a neutral position to avoid neck strain.",
			Instructions: "Go down onto the floor on all fours, lift an alternating arm and leg straight out from your body off the floor simultaneously, repeat on the other side.",
		},
		{
			VideoID:      "9A9PdNB3N_I",
			Name:         "Straddle Sit Ups",
			Category:     "core",
			Description:  "A sit-up variation with legs spread wide.",
			Tips:         "Reach between your legs and beyond. Use your core to sit all the way up, not your momentum.",
			Instructions: "Lie on your back with your legs in a wide 'V' position. Perform a sit-up and reach forward.",
		},
		{
			VideoID:      "8zmy8uvF-EE",
			Name:         "Starjumps",
			Category:     "cardio",
			Description:  "Cardio exercise for full-body conditioning.",
			Tips:         "Land softly with bent knees. Maintain a consistent rhythm throughout the exercise.",
			Instructions: "Start in a standing position, then jump up, spreading your arms and legs wide like a star. Land softly.",
		},
		{
			VideoID:      "HUZKz6RlOic",
			Name:         "Standing Mountain Climbers",
			Category:     "cardio",
			Description:  "A high-intensity cardio exercise performed from a standing position.",
			Tips:         "Swapping legs drive your knees up toward your chest as quickly as possible. Keep your core tight.",
			Instructions: "Stand and alternate bringing your knees up toward your chest, as if running in place, moving opposite arms as you do.",
		},
		{
			VideoID:      "-WyvwUiW9j0",
			Name:         "Squat Twists",
			Category:     "full_body",
			Description:  "A dynamic exercise that combines a squat with a twist.",
			Tips:         "Maintain good squat form, then twist your body 180 degrees as you stand up. Keep the movement fluid.",
			Instructions: "Perform a squat, and as you stand, twist your body 180 degrees, making sure you push off a different leg each twist.",
		},
		{
			VideoID:      "P8QVWzEHbIQ",
			Name:         "Squat Kicks",
			Category:     "legs",
			Description:  "A dynamic exercise combining a squat with a kick.",
			Tips:         "After standing from the squat, kick with control. Alternate which leg you kick with.",
			Instructions: "Perform a squat, and as you stand up, kick one leg forward or to the side.",
		},
		{
			VideoID:      "yqpG-qdXbSk",
			Name:         "Squat Jumps",
			Category:     "legs",
			Description:  "A plyometric exercise for leg power.",
			Tips:         "Lower into a full squat before exploding upward. Land softly to protect your joints.",
			Instructions: "Perform a squat, then jump up as high as you can. Land softly and immediately lower into the next squat.",
		},
		{
			VideoID:      "AfpEkdD6OGc",
			Name:         "Sprints",
			Category:     "cardio",
			Description:  "High-intensity running in place.",
			Tips:         "Move your feet as quickly as possible and pump your arms for maximum intensity.",
			Instructions: "Run in place as fast as you can for the specified duration.",
		},
		{
			VideoID:      "gnxXD85hutk",
			Name:         "Sprawls",
			Category:     "cardio",
			Description:  "A variation of a burpee without the jump or press up.",
			Tips:         "Move quickly from the standing to the lying position. Keep your core engaged.",
			Instructions: "Start standing, drop down and kick your feet back into a lying position, then jump your feet back in and stand up.",
		},
		{
			VideoID:      "8lRSFSpO6SU",
			Name:         "Ski Jumps",
			Category:     "cardio",
			Description:  "A plyometric exercise that simulates ski jumps for cardio and leg strength.",
			Tips:         "Use your arms to help with momentum and balance. Land softly on the balls of your feet.",
			Instructions: "Jump from side to side, as if jumping over a line on the floor.",
		},
		{
			VideoID:      "eJlbNn2H3FQ",
			Name:         "Sit Up Jabs",
			Category:     "core",
			Description:  "A sit-up variation that incorporates punching for an added cardio element.",
			Tips:         "Perform a sit-up and as you reach the top, throw a series of quick jabs forward.",
			Instructions: "Perform a sit-up, and at the top, punch your hands forward before lowering back down.",
		},
		{
			VideoID:      "csddipB7v80",
			Name:         "Scissors",
			Category:     "core",
			Description:  "A core exercise that strengthens the lower abs.",
			Tips:         "Keep your lower back pressed into the floor. The closer to the floor your legs are, the more challenging it is.",
			Instructions: "Lie on your back and lift your legs. Scissor them left and right, alternating in a controlled motion.",
		},
		{
			VideoID:      "q7eSuNJ_H8Y",
			Name:         "Reverse Plank",
			Category:     "core",
			Description:  "An isometric core exercise that targets the core, glutes and shoulders.",
			Tips:         "Keep your body in a straight line from head to heels. Squeeze your glutes to maintain the position.",
			Instructions: "From a high plank position, alternate either side into a reverse plank, lift your hips until your body forms a straight line.",
		},
		{
			VideoID:      "erKTtXZCcfA",
			Name:         "Reverse Lunge Twist",
			Category:     "legs",
			Description:  "A reverse lunge with a torso twist for added core work.",
			Tips:         "As you twist, make sure to keep your hips facing forward. The twist should come from your torso.",
			Instructions: "Step back into a lunge, and at the bottom of the lunge, twist your torso toward the front knee.",
		},
		{
			VideoID:      "o_Ro4FMXLFE",
			Name:         "Reverse Lunge",
			Category:     "legs",
			Description:  "A lunge variation where you step backward.",
			Tips:         "Keep your front knee directly over your ankle. Step far enough back that your back knee is under your hip.",
			Instructions: "Step backward with one leg and lower into a lunge, then return to the starting position.",
		},
		{
			VideoID:      "gseysUqe-1I",
			Name:         "Press Ups",
			Category:     "upper_body",
			Description:  "Standard bodyweight press up.",
			Tips:         "Keep your body in a straight line from head to heels. Lower your chest to the floor and push back up.",
			Instructions: "From a high plank position, lower your chest toward the floor and then push back up.",
		},
		{
			VideoID:      "Gh0nFZZLPQM",
			Name:         "Press Ups (on Knees)",
			Category:     "upper_body",
			Description:  "A modified press up for beginners or those building strength.",
			Tips:         "Keep your core tight and your back straight, even though your knees are on the floor. Don't let your hips sag.",
			Instructions: "From a high plank position with knees on the floor, lower your chest toward the ground and push back up.",
		},
		{
			VideoID:      "m0XcSTbvsb8",
			Name:         "Press Up Twists",
			Category:     "upper_body",
			Description:  "A press up variation that adds a torso twist for core engagement.",
			Tips:         "As you twist, stack your hips and open your chest to the side. Keep your core engaged to prevent wobbling.",
			Instructions: "Perform a press up, and at the top, twist your torso to one side, raising one arm to the ceiling.",
		},
		{
			VideoID:      "CJpvGfmHtxg",
			Name:         "Plyo Press Ups",
			Category:     "upper_body",
			Description:  "An explosive press up variation for power and speed.",
			Tips:         "Explode off the ground with enough force for your hands to leave the floor. Land softly and with control.",
			Instructions: "Perform a press up, but push off the ground with enough force to lift your hands off the floor.",
		},
		{
			VideoID:      "CToaa3bcnpQ",
			Name:         "Plank Shoulder Taps",
			Category:     "core",
			Description:  "A core stability exercise that challenges balance.",
			Tips:         "Keep your hips as still as possible. The goal is to avoid rocking your body from side to side.",
			Instructions: "From a high plank position, tap your opposite shoulder with one hand, alternating sides.",
		},
		{
			VideoID:      "RWud04dw3ng",
			Name:         "Plank Leg Raises",
			Category:     "core",
			Description:  "A plank variation that strengthens the glutes and core.",
			Tips:         "Maintain a perfectly straight plank position. Don't let your hips twist as you lift your leg.",
			Instructions: "From a high plank position, lift one leg straight up a few inches, hold, then lower it. Alternate legs.",
		},
		{
			VideoID:      "dSQMe4X5jBw",
			Name:         "Plank Jabs",
			Category:     "core",
			Description:  "A plank variation that engages the core and shoulders with punching motions.",
			Tips:         "Keep your hips stable and your core engaged. Punch straight forward and with control.",
			Instructions: "From a high plank position, punch one arm straight forward, alternating sides.",
		},
		{
			VideoID:      "LO6ZguR9xec",
			Name:         "Pike Jumps",
			Category:     "core",
			Description:  "A dynamic jump that raises the heart rate.",
			Tips:         "Jump your legs and feet out with quick, controlled movement.",
			Instructions: "From a standing position, jump both legs out and try to touch your toes.",
		},
		{
			VideoID:      "h8tmGnVXqQY",
			Name:         "Overhead Jabs",
			Category:     "cardio",
			Description:  "A cardio exercise that involves quick, overhead punching.",
			Tips:         "Keep your arms up and punch with quick, powerful movements.",
			Instructions: "Stand with your feet shoulder-width apart and punch your hands overhead quickly and continuously. Whilst running on the spot",
		},
		{
			VideoID:      "mwLO_qIuqa8",
			Name:         "Overhead Jabs (Fast)",
			Category:     "cardio",
			Description:  "A higher-intensity version of overhead jabs.",
			Tips:         "Focus on speed and maintaining a high tempo. Keep your core engaged for stability.",
			Instructions: "Perform overhead jabs at a fast, continuous pace.",
		},
		{
			VideoID:      "gDKjAOGqt_0",
			Name:         "Oblique Press Ups",
			Category:     "upper_body",
			Description:  "A press up variation that targets the obliques.",
			Tips:         "Perform a press up, and as you push up, bring one knee toward the opposite elbow. Maintain a straight back and engage your core",
			Instructions: "Perform a press up, and at the top, bring one knee to the opposite elbow. Alternate sides.",
		},
		{
			VideoID:      "5jwecucBurE",
			Name:         "Oblique Plank",
			Category:     "core",
			Description:  "A core exercise that targets the obliques and abdominals.",
			Tips:         "Focus on lifting with your core. Keep your hips and body in a straight line.",
			Instructions: "In a high plank position, lift your leg out to the side, bringing your knee towards your elbow. Alternate sides",
		},
		{
			VideoID:      "sEm2wiQbRjE",
			Name:         "Oblique Hops",
			Category:     "cardio",
			Description:  "A plyometric exercise for the core and legs.",
			Tips:         "Keep your feet together and hop side to side with a small, controlled motion.",
			Instructions: "In a high plank position, with feet together and hop from side to side. Returning to the start each time",
		},
		{
			VideoID:      "waIht9sWJZU",
			Name:         "Moving Press Ups",
			Category:     "upper_body",
			Description:  "A dynamic press up variation where you move from side to side.",
			Tips:         "As you move, keep your core tight to prevent your hips from rocking. Maintain a steady pace.",
			Instructions: "Perform a press up, then move to the side and perform another press up. Continue moving from side to side.",
		},
		{
			VideoID:      "_OsY3ruw3lU",
			Name:         "Mountain Climbers",
			Category:     "cardio",
			Description:  "Cardio exercise in plank position",
			Tips:         "Keep core engaged, alternate legs quickly.",
			Instructions: "In plank position, alternate bringing knees toward chest.",
		},
		{
			VideoID:      "xem5n_mBlYo",
			Name:         "March Step",
			Category:     "cardio",
			Description:  "A low-impact cardio exercise that serves as a warmup or cool-down.",
			Tips:         "Keep a steady pace and use your arms to help with momentum.",
			Instructions: "March in place, bringing your knees up to hip height.",
		},
		{
			VideoID:      "J4zvmrNIS4w",
			Name:         "Lunges",
			Category:     "legs",
			Description:  "Forward lunges",
			Tips:         "Step forward, both knees at 90 degrees, alternate legs.",
			Instructions: "Step forward with one leg, lower until both knees are bent at 90 degrees.",
		},
		{
			VideoID:      "gLRYHREAUuQ",
			Name:         "Leg Raises",
			Category:     "core",
			Description:  "A core exercise that targets the lower abs.",
			Tips:         "Keep your lower back pressed into the floor. If this is too difficult, bend your knees slightly.",
			Instructions: "Lie on your back with legs straight. Slowly raise your legs toward the ceiling and lower them back down.",
		},
		{
			VideoID:      "s6dg4l-M3hs",
			Name:         "Leg Circles",
			Category:     "core",
			Description:  "A core exercise that strengthens the lower abs and hips.",
			Tips:         "Keep your lower back on the floor throughout the movement. Perform small, controlled circles.",
			Instructions: "Lie on your back with legs raised. Draw small circles with your legs, keeping them together.",
		},
		{
			VideoID:      "nAKm5EnRgX4",
			Name:         "Lateral Lunges",
			Category:     "legs",
			Description:  "A lunge variation that targets the inner and outer thighs.",
			Tips:         "Keep your back straight and push your hips back as you lunge to the side. Keep the other leg straight.",
			Instructions: "Step to the side with one leg and lower your hips, as if sitting back into a chair.",
		},
		{
			VideoID:      "WpxHSjZVFDQ",
			Name:         "Knees to Chest",
			Category:     "core",
			Description:  "A core exercise that targets the lower abs.",
			Tips:         "Keep your core tight and your back flat on the floor. Bring your knees to your chest with a controlled motion.",
			Instructions: "Lie on your back, lift your head and shoulders slightly and bring your knees to your chest.",
		},
		{
			VideoID:      "FYgLvCSy_Yo",
			Name:         "Knee Twists",
			Category:     "core",
			Description:  "A core exercise that targets the obliques.",
			Tips:         "Keep your arms and shoulders on the floor. Focus on rotating your hips and knees to the side.",
			Instructions: "Lie on your back with knees bent and feet on the floor. Lower your knees to one side, then the other.",
		},
		{
			VideoID:      "paCpuYxpDqo",
			Name:         "Jump Lunge",
			Category:     "legs",
			Description:  "A plyometric lunge for explosive power and cardio.",
			Tips:         "Explode upward from the lunge and switch your legs in the air. Land softly with knees bent.",
			Instructions: "From a lunge position, jump up and switch your legs in mid-air, landing in a lunge with the opposite leg forward.",
		},
		{
			VideoID:      "G7oXBWUfR78",
			Name:         "Jogging on the Spot",
			Category:     "cardio",
			Description:  "A low-impact cardio exercise.",
			Tips:         "Keep a light, steady pace. Use your arms to help with momentum.",
			Instructions: "Jog in place, lifting your feet slightly off the ground.",
		},
		{
			VideoID:      "ynFa3MQCwVY",
			Name:         "Jack Knife",
			Category:     "core",
			Description:  "A full-body core exercise.",
			Tips:         "Keep your legs and arms straight. Use your core to bring your upper and lower body toward each other.",
			Instructions: "Lie on your back with arms and legs extended. Simultaneously raise your arms and legs to meet in the middle.",
		},
		{
			VideoID:      "Bz-g0ifHORg",
			Name:         "Inch Worm",
			Category:     "full_body",
			Description:  "A dynamic stretching and core strengthening exercise.",
			Tips:         "Keep your legs as straight as possible. Walk your hands as far out as you can, then walk your legs to meet them.",
			Instructions: "Start standing, bend down and walk your hands out into a plank, then walk your feet toward your hands.",
		},
		{
			VideoID:      "nz4-POvt1IU",
			Name:         "H.O.G. Press Ups",
			Category:     "upper_body",
			Description:  "A press up variation focusing on full range.",
			Tips:         "H.O.G. stands for 'Hands Off the Ground.' To help focus on full range.",
			Instructions: "Perform a press up and lower all the way to the ground. Make sure your hands leave the ground and push back up.",
		},
		{
			VideoID:      "gtquD3Dxr-8",
			Name:         "High Knees",
			Category:     "cardio",
			Description:  "A high-intensity cardio exercise.",
			Tips:         "Drive your knees up to hip height. Use your arms to help with momentum.",
			Instructions: "Run in place, bringing your knees as high as you can with each step.",
		},
		{
			VideoID:      "g-CiUKK3h6g",
			Name:         "High Low Plank",
			Category:     "core",
			Description:  "A dynamic plank exercise that transitions between a high plank and a forearm plank.",
			Tips:         "Keep your hips as still as possible. Move with control, not speed.",
			Instructions: "Start in a high plank, drop to a forearm plank, then press back up to a high plank.",
		},
		{
			VideoID:      "A18hRNIHJaI",
			Name:         "Heel Taps",
			Category:     "core",
			Description:  "An oblique exercise that strengthens the sides of the core.",
			Tips:         "Crunch your upper body slightly and reach your hand down to tap your heel. Keep your neck relaxed.",
			Instructions: "Lie on your back with knees bent, feet on the floor. Reach down to tap your left heel with your left hand, then your right heel with your right hand.",
		},
		{
			VideoID:      "Q5ZHXKFM8GU",
			Name:         "Heel Flicks",
			Category:     "cardio",
			Description:  "A cardio exercise that targets the hamstrings.",
			Tips:         "Keep your core engaged. Aim to kick your heels all the way back to touch your glutes.",
			Instructions: "Run in place, kicking your heels back toward your glutes with each step.",
		},
		{
			VideoID:      "WAOSgMdm7B0",
			Name:         "Half Sit Ups",
			Category:     "core",
			Description:  "A modified sit-up that focuses on the upper abs.",
			Tips:         "Only lift your upper back off the floor, engaging your abs. Avoid pulling on your neck.",
			Instructions: "Lie on your back with knees bent. Lift your shoulders off the floor, engaging your core, and then lower back down.",
		},
		{
			VideoID:      "xB2kVlli3AM",
			Name:         "Glute Bridges",
			Category:     "legs",
			Description:  "Glute strengthening exercise",
			Tips:         "Squeeze glutes at the top, hold for a few seconds, keep feet flat on ground.",
			Instructions: "Lie on back, bend knees, lift hips toward ceiling.",
		},
		{
			VideoID:      "nDyG0SO4SJ4",
			Name:         "Get Ups",
			Category:     "full_body",
			Description:  "A full-body exercise that involves standing up from a lying position.",
			Tips:         "Use your core and leg strength to stand up with control. No hands if you can manage!",
			Instructions: "From a lying position, stand up without using your hands, then lie back down. Repeat.",
		},
		{
			VideoID:      "FVop9q2WZaY",
			Name:         "Flutter Kicks",
			Category:     "core",
			Description:  "A core exercise that targets the lower abs and hip flexors.",
			Tips:         "Keep your lower back pressed into the floor. Make the kicks small and controlled.",
			Instructions: "Lie on your back and lift your legs. Perform small, quick kicks up and down, alternating legs.",
		},
		{
			VideoID:      "SQ8RV0Glg6s",
			Name:         "Explosive Starjumps",
			Category:     "cardio",
			Description:  "A high-intensity version of a star jump for maximum cardio.",
			Tips:         "Jump as high as you can and spread your limbs as wide as possible for a full extension.",
			Instructions: "From a squat position, hands down low, perform a star jump with maximum effort and height on each repetition.",
		},
		{
			VideoID:      "f-VwwnlzVnM",
			Name:         "Elbows to Knee",
			Category:     "cardio",
			Description:  "A cardio and core exercise that brings opposite elbow to knee.",
			Tips:         "Keep a quick tempo. Twist your torso to engage your obliques.",
			Instructions: "Staay light on your feet. Lift one knee and twist your torso to bring the opposite elbow to the knee. Alternate sides.",
		},
		{
			VideoID:      "dxtScFd1mhM",
			Name:         "Dorsal Raises",
			Category:     "upper_body",
			Description:  "A back-strengthening exercise.",
			Tips:         "Keep your head in a neutral position. Focus on lifting with your back, not your neck.",
			Instructions: "Lie on your stomach and lift your chest and shoulders off the floor, engaging your back muscles.",
		},
		{
			VideoID:      "fg2pvXt5HQY",
			Name:         "Donkey Kicks",
			Category:     "legs",
			Description:  "A glute-strengthening exercise.",
			Tips:         "Keep your back flat and your core engaged. Squeeze your glute at the top of the movement.",
			Instructions: "On your hands and knees, lift one leg and kick it straight up, then return to the starting position.",
		},
		{
			VideoID:      "GuZe9itNvZs",
			Name:         "Diamond Sit Ups",
			Category:     "core",
			Description:  "A sit-up variation with feet touching in a diamond shape.",
			Tips:         "The diamond shape of your legs allows for greater core activation. Reach your hands past your feet.",
			Instructions: "Lie on your back with the soles of your feet together. Perform a sit-up and reach toward or past your feet and head.",
		},
		{
			VideoID:      "cLqsHwtlNWI",
			Name:         "Crunches",
			Category:     "core",
			Description:  "A basic abdominal exercise.",
			Tips:         "Keep your lower back on the floor. Focus on using your core to lift your shoulders off the ground. Try and not let your feet drop",
			Instructions: "Lie on your back with legs straight. Lift your shoulders and yours knees to meet, engaging your core.",
		},
		{
			VideoID:      "boRcEnMEj5E",
			Name:         "Cross Jabs",
			Category:     "cardio",
			Description:  "A cardio exercise that simulates boxing punches.",
			Tips:         "Twist your torso with each punch. Keep the pace quick for cardio benefits.",
			Instructions: "Stand and punch forward across your body, alternating arms quickly.",
		},
		{
			VideoID:      "PYoNax1_w74",
			Name:         "Cross Jacks",
			Category:     "cardio",
			Description:  "A cardio exercise similar to jumping jacks, but crossing legs.",
			Tips:         "Coordinate your arm and leg movements. Land softly and with control.",
			Instructions: "Jump, crossing one leg over the other and one arm over the head, then jump back to the start.",
		},
		{
			VideoID:      "YstSKtOL4oE",
			Name:         "Crab Walks",
			Category:     "full_body",
			Description:  "A full-body exercise that strengthens the shoulders, triceps and core.",
			Tips:         "Keep your hips off the floor. Walk with opposite hand and foot simultaneously.",
			Instructions: "Start in a 'crab' position, then walk forward or backward, alternating hands and feet.",
		},
		{
			VideoID:      "W5bOlVTG_N0",
			Name:         "Calf Raises",
			Category:     "legs",
			Description:  "An exercise to strengthen the calf muscles.",
			Tips:         "Go all the way up on your toes and all the way down. Hold for a moment at the top.",
			Instructions: "Stand and lift your heels off the floor, rising onto the balls of your feet.",
		},
		{
			VideoID:      "DTiQ7mImqto",
			Name:         "Calf Raises Right",
			Category:     "leg",
			Description:  "A single-leg calf raise on the right leg.",
			Tips:         "Use a wall for balance if needed. Focus on the contraction in your calf muscle.",
			Instructions: "Stand on your right leg and perform a calf raise.",
		},
		{
			VideoID:      "OjUmN3JA0ss",
			Name:         "Calf Raises Left",
			Category:     "legs",
			Description:  "A single-leg calf raise on the left leg.",
			Tips:         "Use a wall for balance if needed. Focus on the contraction in your calf muscle.",
			Instructions: "Stand on your left leg and perform a calf raise.",
		},
		{
			VideoID:      "O-JvBgG0QRk",
			Name:         "Calf Jumps",
			Category:     "cardio",
			Description:  "A plyometric exercise for the calves and ankles.",
			Tips:         "Keep your knees mostly straight and perform small, quick hops using only your calves.",
			Instructions: "Jump up and down using only your calves, keeping your knees relatively straight.",
		},
		{
			VideoID:      "ILfLsZieAMg",
			Name:         "Burpees",
			Category:     "full_body",
			Description:  "Full body conditioning exercise",
			Tips:         "Explosive movement, full range of motion, maintain form.",
			Instructions: "Start standing, drop to the floor, jump feet forward, jump up.",
		},
		{
			VideoID:      "F9gX8P8lCc0",
			Name:         "Burpees (modified)",
			Category:     "full_body",
			Description:  "A lower-impact burpee variation without the full press up and jump.",
			Tips:         "Step your feet back one at a time instead of jumping. Omit the press up if needed.",
			Instructions: "Start standing, step feet back to a plank, step them back in, and stand up.",
		},
		{
			VideoID:      "rs8lPLmQK-I",
			Name:         "Burpee Tucks",
			Category:     "full_body",
			Description:  "A burpee variation with a tuck jump for added intensity.",
			Tips:         "As you jump up from the burpee, tuck your knees to your chest.",
			Instructions: "Perform a burpee, and instead of a regular jump, perform a tuck jump at the end.",
		},
		{
			VideoID:      "WG3QArwVmpw",
			Name:         "Broad Jumps",
			Category:     "cardio",
			Description:  "A plyometric exercise for explosive leg power.",
			Tips:         "Swing your arms back and forth to generate momentum. Land softly with bent knees.",
			Instructions: "Jump forward as far as you can from a standing position. Land and immediately repeat.",
		},
		{
			VideoID:      "6lDkwpUpRJc",
			Name:         "Burpee Sprints",
			Category:     "cardio",
			Description:  "A burpee variation that incorporates a sprint.",
			Tips:         "Perform a burpee, then sprint on the spot 3-4 steps before repeating.",
			Instructions: "Perform a burpee, then sprint on the spot, moving your feet as quickly as possible and repeat.",
		},
		{
			VideoID:      "g9AtnGRgCbI",
			Name:         "Box Jumps",
			Category:     "cardio",
			Description:  "A plyometric exercise for power and agility.",
			Tips:         "Use your arms to help propel yourself around the floor in a 'box'. If limited space keep the box small.",
			Instructions: "Jump forward, left, back and right. Land softly with both feet.",
		},
		{
			VideoID:      "KkumMUmVlzs",
			Name:         "Bicycles",
			Category:     "core",
			Description:  "A core exercise that targets the obliques.",
			Tips:         "Move your legs in a pedaling motion. Bring your chest up to meet your knees.",
			Instructions: "Lie on your back, pedal your legs and bring your torso to meet your knees.",
		},
		{
			VideoID:      "_0mTRFFa_y0",
			Name:         "Bicycle Legs",
			Category:     "core",
			Description:  "A core exercise that targets the lower abs and hip flexors.",
			Tips:         "Move your legs in a pedaling motion. Keep your lower back pressed into the floor.",
			Instructions: "Lie on your back and move your legs in a cycling motion, as if you were pedaling a bike.",
		},
		{
			VideoID:      "76DMzTWs5WQ",
			Name:         "Belt Kicks",
			Category:     "cardio",
			Description:  "A cardio exercise that involves a kicking motion.",
			Tips:         "Kick with control. Engage your core to help with the balance.",
			Instructions: "Stand and perform quick kicks out to the front.",
		},
		{
			VideoID:      "JLZzXq8cKJM",
			Name:         "Bearcrawls",
			Category:     "full_body",
			Description:  "A full-body exercise that strengthens the core, shoulders and legs.",
			Tips:         "Keep your knees low and your back flat. Move with opposite hand and foot simultaneously.",
			Instructions: "Start on your hands and knees. Lift your knees off the floor and crawl forward and backward.",
		},
		{
			VideoID:      "nzOLTP3Kw9c",
			Name:         "Back Drills",
			Category:     "full_body",
			Description:  "A dynamic exercise that strengthens the body.",
			Tips:         "Focus on control and stability.",
			Instructions: "Lie on your back and spread your arms out and get back up any way you can.",
		},
		{
			VideoID:      "QgHkhdP8CQ8",
			Name:         "Arm Circles Forwards",
			Category:     "upper_body",
			Description:  "A dynamic shoulder warm-up or cool-down.",
			Tips:         "Keep your arms straight and make large, controlled circles.",
			Instructions: "Stand with arms straight out to your sides. Make circles forward.",
		},
		{
			VideoID:      "X6KHNHNCvD4",
			Name:         "Arm Circle Backwards",
			Category:     "upper_body",
			Description:  "A dynamic shoulder warm-up or cool-down.",
			Tips:         "Keep your arms straight and make large, controlled circles.",
			Instructions: "Stand with arms straight out to your sides. Make circles backward.",
		},
		{
			VideoID:      "cEaVvERgpyI",
			Name:         "Ab Twists",
			Category:     "core",
			Description:  "A core exercise for the obliques.",
			Tips:         "Keep your back straight and your core engaged. Twist your torso from side to side.",
			Instructions: "Sit with your knees bent and lean back slightly. Twist your torso as you sit up to one side and repeat on the other side.",
		},
	}

	// Create exercises in database
	for _, exercise := range exercises {
		var existingExercise models.Exercise
		if err := DB.Where("name = ?", exercise.Name).First(&existingExercise).Error; err != nil {
			if err := DB.Create(&exercise).Error; err != nil {
				log.Printf("Failed to create exercise %s: %v", exercise.Name, err)
			} else {
				log.Printf("Created exercise: %s", exercise.Name)
			}
		} else {
			log.Printf("Exercise already exists: %s", exercise.Name)
		}
	}

	log.Println("Linking exercise modifications...")

	modifications := map[string]string{
		"Press Ups":                "Press Ups (on Knees)",
		"Burpees":                  "Burpees (modified)",
		"Burpee Tucks":             "Burpees (modified)",
		"Wide Arm Press Ups":       "Wide Arm Press Ups (on Knees)",
		"Tricep Dips (with Chair)": "Tricep Dips (Floor)",
		"Diamond Press Ups":        "Diamond Press Ups (on Knees)",
		"Tuck Jumps":               "Squat Jumps",
		"Explosive Starjumps":      "Starjumps",
		"Press Up Twists":          "Press Up Twists (on Knees)",
		"Pike Jumps":               "Tuck Jumps",
		"Jump Lunge":               "Lunges",
		"H.O.G. Press Ups":         "H.O.G. Press Ups (on Knees)",
		"Bicycles":                 "Bicycle Legs",
		"Bicycle Legs":             "Crunches",
	}

	for original, modified := range modifications {
		linkExerciseToModification(DB, original, modified, 1)
	}
	linkExerciseToModification(DB, "Tricep Dips (Floor)", "Diamond Press Ups", 2)
}

func linkExerciseToModification(db *gorm.DB, originalName, modifiedName string, level int) {
	originalID, err := getExerciseIDByName(db, originalName)
	if err != nil {
		log.Printf("Failed to find '%s' to link modification: %v", originalName, err)
		return
	}

	modifiedID, err := getExerciseIDByName(db, modifiedName)
	if err != nil {
		log.Printf("Failed to find '%s' to link: %v", modifiedName, err)
		return
	}

	if originalID != 0 && modifiedID != 0 {
		updateColumn := "modification_id"
		if level == 2 {
			updateColumn = "modification_id2"
		}

		if err := db.Model(&models.Exercise{}).Where("id = ?", originalID).Update(updateColumn, modifiedID).Error; err != nil {
			log.Printf("Failed to link '%s' to modification at level %d: %v", originalName, level, err)
		} else {
			log.Printf("Successfully linked '%s' to '%s' at level %d.", originalName, modifiedName, level)
		}
	}
}
