namespace: lmw-fitness
env: production
allowedOrigin: https://www.lmwfitness.co.uk

api:
  host: api.lmwfitness.co.uk
  port: 8082
  type: NodePort  
  nodePort: 30260
  path: /api/
  pathType: Prefix

image:
  repository: lmwcode/lmw_fitness_api
  tag: v1.9.0
  pullPolicy: Always

replicaCount: 1

database:
  name: LMWfitness
  user: postgres
  port: 5432
  type: ClusterIP
  sslMode: disable

storage:
  storageClass: standard

smtp:
  host: smtp.ionos.co.uk
  port: 587
  username: info@lmwfitness.co.uk
  from: info@lmwfitness.co.uk
  to: info@lmwfitness.co.uk

livenessProbe:
  endpoint: /api/health/live
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  endpoint: /api/health/ready
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1