apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SMTP_PASSWORD: anBxLXhldzVQQUU=
  RECAPTCHA_SECRET: NkxkbjMtMHFBQUFBQUdMUTZIMi16ZEJGTFBIcTdxMHpDNlZlc0FCUQ==
  DB_PASSWORD: UmVuZWdhZGUxODch  
  ACCESS_SECRET_KEY: dGhpc2lzbm90YXZlcnlnb29kYWNjZXNzc2VjcmV0a2V5
  REFRESH_SECRET_KEY: dGhpc2lzbm90YXZlcnlnb29kcmVmcmVzaHNlY3JldGtleQ==