apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmw-fitness-backend-deployment
  namespace: lmw-fitness
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: LMW-fitness-backend
    meta.helm.sh/release-namespace: lmw-fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-lmw-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: backend
        image: lmwcode/lmw_fitness_api:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: lmw-fitness-configmap-backend
        env:
         - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lmw-fitness-secrets
              key: DB_PASSWORD

        - name: SMTP_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: lmw-fitness-secrets
              key: SMTP_PASSWORD

        - name: RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: lmw-fitness-secrets
              key: RECAPTCHA_SECRET
        
        - name: ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: lmw-fitness-secrets
              key: ACCESS_SECRET_KEY

        - name: REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: lmw-fitness-secrets
              key: REFRESH_SECRET_KEY
        
        readinessProbe:
          httpGet:
            path: /api/
            port: 8082
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 120
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/
            port: 8082
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 120
          failureThreshold: 3