apiVersion: v1
kind: Service
metadata:
  name: lmw-fitness-backend-service
  namespace: lmw-fitness
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: LMW-fitness-backend
    meta.helm.sh/release-namespace: lmw-fitness
spec:
  selector:
    app: backend
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP