namespace: lmw-fitness
GO_ENV: production

api:
  port: 8082

image:
  repository: lmwcode/lmw_fitness_api
  tag: v3.0.0
  pullPolicy: Always

replicaCount: 1

database:
  name: LMWfitness
  user: postgres
  port: 5432
  sslMode: disable

smtp:
  host: smtp.ionos.co.uk
  port: 587
  username: info@lmwfitness.co.uk
  from: info@lmwfitness.co.uk
  to: info@lmwfitness.co.uk